# Generated by Django 2.1.5 on 2019-04-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dept_full_name',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
    ]
