# Generated by Django 2.1.5 on 2019-04-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_department_dept_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_full_name',
            field=models.CharField(max_length=100),
        ),
    ]
