# Generated by Django 2.1.5 on 2019-03-23 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
        ('qnppr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcode', models.CharField(max_length=100)),
                ('subname', models.CharField(max_length=100)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Department')),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qnppr.Semester')),
            ],
        ),
    ]
