# Generated by Django 2.1.5 on 2019-03-26 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnppr', '0003_module'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Module',
        ),
    ]
