# Generated by Django 2.1.5 on 2019-03-26 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qnppr', '0007_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Co',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_name', models.CharField(max_length=100)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qnppr.Module')),
                ('sub_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qnppr.Subject')),
            ],
        ),
    ]
