# Generated by Django 2.1.5 on 2019-03-26 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnppr', '0008_co'),
    ]

    operations = [
        migrations.RenameField(
            model_name='co',
            old_name='co_name',
            new_name='co_cd_name',
        ),
        migrations.RemoveField(
            model_name='co',
            name='module',
        ),
        migrations.RemoveField(
            model_name='co',
            name='sub_code',
        ),
    ]
