# Generated by Django 2.1.5 on 2019-03-26 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qnppr', '0009_auto_20190326_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Co_mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_desc', models.CharField(max_length=100)),
                ('co_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qnppr.Co')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qnppr.Module')),
                ('sub_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qnppr.Subject')),
            ],
        ),
    ]
