# Generated by Django 2.1.5 on 2019-03-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnppr', '0010_co_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blooms_lvl_tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blm_lvl_name', models.CharField(max_length=100)),
            ],
        ),
    ]
