# Generated by Django 2.1.5 on 2019-03-29 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnppr', '0011_blooms_lvl_tbl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blooms_lvl_tbl',
            new_name='Blooms_lvl',
        ),
    ]
