# Generated by Django 2.1.5 on 2019-04-01 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
        ('qnppr', '0014_marks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marks',
            new_name='Mark',
        ),
    ]
