# Generated by Django 2.1.5 on 2019-04-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnppr', '0018_auto_20190410_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='fig',
            field=models.ImageField(blank=True, upload_to='question_fig/'),
        ),
    ]
