# Generated by Django 2.1.5 on 2019-04-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exm_typ_name', models.CharField(max_length=100)),
            ],
        ),
    ]
