# Generated by Django 2.1.5 on 2019-04-29 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qnppr', '0019_auto_20190410_1138'),
        ('users', '0005_auto_20190424_0954'),
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100)),
                ('attachment', models.FileField(upload_to='question_papers/')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Department')),
                ('exm_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.ExamType')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qnppr.Module')),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qnppr.Semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qnppr.Subject')),
            ],
        ),
    ]
